MvcMusicList/Models/MusicList.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MvcMusicList.Models
{
	public class MusicList
	{
		public int ID { get; set; }

		[Required, StringLength(60, MinimumLength = 3)]
		public string Artiste { get; set; }
		[Required]
		public string Album { get; set; }
		[Required]
		public string Genre { get; set; }
		[Required]
		public int Annee { get; set; }
		public string Vues { get; set; }
	
	}

	public class MusicListDBContext : DbContext
	{
		public DbSet<MusicList> MusicLists { get; set; }
	}
}

MvcMusicList/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcMusicList.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

MvcMusicList/Controllers/MusicListsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using PagedList;
using System.Web.Mvc;
using MvcMusicList.Models;

namespace MvcMusicList.Controllers
{
    public class MusicListsController : Controller
    {
        private MusicListDBContext db = new MusicListDBContext();

		// GET: MusicLists
		public ViewResult Index(string musicListGenre, string searchString, int? anneeSorties, string sortOrder)
        {
			ViewBag.CurrentSort = sortOrder;
			ViewBag.NameSortParam = string.IsNullOrEmpty(sortOrder) ? "ariste_desc" : "";
			ViewBag.AnneeSortParam = sortOrder == "Annee" ? "annee_desc" : "Annee"; 
		
			var GenreLst = new List<string>();

			var GenreQry = from d in db.MusicLists
						   orderby d.Genre
						   select d.Genre;

			GenreLst.AddRange(GenreQry.Distinct());
			ViewBag.musicListGenre = new SelectList(GenreLst);

			var AnneeLst = new List<int>();

			var AnneeQry = from a in db.MusicLists
						   orderby a.Annee
						   select a.Annee;

			AnneeLst.AddRange(AnneeLst.Distinct());
			ViewBag.anneeSorties = new SelectList(AnneeLst); 

			var musicLists = from m in db.MusicLists
							 select m;
		

			musicLists = this.GetListsMusicsByArtistName(searchString, musicLists);

			musicLists = this.GetMusicListsByGenre(musicListGenre, musicLists);

			musicLists = this.GetMusicListsByAnnee(anneeSorties, musicLists);

			musicLists = this.MakeSortOrder(sortOrder, musicLists);

			
			
			return View(musicLists);
        }

		public IQueryable<MusicList> GetListsMusicsByArtistName (string searchString, IQueryable<MusicList> musicLists)
		{
			if (!string.IsNullOrEmpty(searchString))
			{
				return musicLists.Where(s => s.Artiste.Contains(searchString));
			}
			return musicLists;
		}

		public IQueryable<MusicList> GetMusicListsByGenre (string musicListGenre, IQueryable<MusicList> musicLists)
		{
			if (!string.IsNullOrEmpty(musicListGenre))
			{
				return musicLists.Where(x => x.Genre == musicListGenre);
			}
			return musicLists;
		}

		public IQueryable<MusicList> GetMusicListsByAnnee (int? anneeSorties, IQueryable<MusicList> musicLists)
		{
			if (anneeSorties != 0 && anneeSorties.HasValue)
			{
				return musicLists.Where(y => y.Annee == anneeSorties.Value);
			}
			return musicLists;
		}

		public IQueryable<MusicList> MakeSortOrder(string sortOrder, IQueryable<MusicList> musicLists)
		{
			switch(sortOrder)
			{
				case "ariste_desc":
					musicLists = musicLists.OrderBy(s => s.Artiste);
					break;
				case "Annee":
					musicLists = musicLists.OrderBy(s => s.Annee);
					break;
				case "annee_desc":
					musicLists = musicLists.OrderByDescending(s => s.Annee);
					break;
				default:
					musicLists = musicLists.OrderByDescending(s => s.Artiste);
					break;
			}

			return musicLists; 
		}

        // GET: MusicLists/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicList musicList = db.MusicLists.Find(id);
            if (musicList == null)
            {
                return HttpNotFound();
            }
            return View(musicList);
        }

        // GET: MusicLists/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MusicLists/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Artiste,Album,Genre,Annee,Vues")] MusicList musicList)
        {
            if (ModelState.IsValid)
            {
                db.MusicLists.Add(musicList);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(musicList);
        }

        // GET: MusicLists/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicList musicList = db.MusicLists.Find(id);
            if (musicList == null)
            {
                return HttpNotFound();
            }
            return View(musicList);
        }

        // POST: MusicLists/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Artiste,Album,Genre,Annee,Vues")] MusicList musicList)
        {
            if (ModelState.IsValid)
            {
                db.Entry(musicList).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(musicList);
        }

        // GET: MusicLists/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicList musicList = db.MusicLists.Find(id);
            if (musicList == null)
            {
                return HttpNotFound();
            }
            return View(musicList);
        }

        // POST: MusicLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MusicList musicList = db.MusicLists.Find(id);
            db.MusicLists.Remove(musicList);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcMusicList/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MvcMusicList/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MvcMusicList/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Musics List</h1>
 </div>

<div class="row">
    <div class="col-md-4">
        <h2>Bienvenue dans ma Liste des chansons</h2>
        <p>
            Musics List est une simple application web qui affiche la liste
            des chansons. Avec elle, vous pouvez Afficher, mettre à jour, voir les informations relatives
            aux artistes et supprimer.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Afficher les musiques</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MvcMusicList/Views/MusicLists/Create.cshtml
@model MvcMusicList.Models.MusicList

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MusicList</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Artiste, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artiste, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Artiste, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Album, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Album, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Album, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Annee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Annee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Annee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vues, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vues, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vues, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcMusicList/Views/MusicLists/Delete.cshtml
@model MvcMusicList.Models.MusicList

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MusicList</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artiste)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artiste)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Album)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Album)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Annee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Annee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vues)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vues)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcMusicList/Views/MusicLists/Details.cshtml
@model MvcMusicList.Models.MusicList

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MusicList</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artiste)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artiste)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Album)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Album)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Annee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Annee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vues)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vues)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcMusicList/Views/MusicLists/Edit.cshtml
@model MvcMusicList.Models.MusicList

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MusicList</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Artiste, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artiste, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Artiste, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Album, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Album, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Album, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Annee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Annee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Annee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vues, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vues, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vues, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcMusicList/Views/MusicLists/Index.cshtml
@model IEnumerable<MvcMusicList.Models.MusicList>


<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css"/>

@{
    ViewBag.Title = "MusicList";
}

<h2>Musics List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
    @using (Html.BeginForm("Index", "MusicLists",FormMethod.Get))
    {
<p>
    Genre: @Html.DropDownList("musicListGenre", "All")
    Artiste: @Html.TextBox("SearchString")
    <input type="submit" value="Filter" />
    Annee de sortie : @Html.TextBox("anneeSorties", "")
    <input type="submit" value="Filter" />
</p>
    }

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Artiste", "Index", new { sortOder = ViewBag.NameSortParam })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Album)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.ActionLink("Annee", "Index", new { sortOder = ViewBag.AnneeSortParam })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vues)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Artiste)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Album)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Annee)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Vues)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

MvcMusicList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Music List</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Musics List", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>